set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk_i]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports rst_n_i]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports btn_n_i]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD TMDS_33} [get_ports tmds_clk_o_p]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD TMDS_33} [get_ports tmds_clk_o_n]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_p[2]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_n[2]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_p[1]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_n[1]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_p[0]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD TMDS_33} [get_ports {tmds_data_o_n[0]}]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports led_o[3]]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports led_o[2]]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports led_o[1]]
set_property -dict {PACKAGE_PIN T12 IOSTANDARD LVCMOS33} [get_ports led_o[0]]

set_false_path -from [get_ports {rst_n_i}]
set_false_path -from [get_ports {btn_n_i}]
set_false_path -to [get_ports {tmds_clk_o_p}]
set_false_path -to [get_ports {tmds_clk_o_n}]
set_false_path -to [get_ports {tmds_data_o_p[*]}]
set_false_path -to [get_ports {tmds_data_o_n[*]}]
set_false_path -to [get_ports {led_o[*]}]
